name: nothingness
description: "Media controller with spectrum visualizer"

publish_to: "none"

version: 1.1.1+3

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  audio_session: ^0.2.2
  file_picker: ^10.3.8
  permission_handler: ^12.0.1
  flutter_soloud: ^3.4.7
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mockito: ^5.6.1
  build_runner: ^2.10.4
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Press Start 2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
