name: nothingness
description: "Media controller with spectrum visualizer"

publish_to: "none"

version: 2.1.17+23

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3
  audio_session: ^0.2.2
  audio_service: ^0.18.18
  file_picker: ^10.3.8
  permission_handler: ^12.0.1
  flutter_soloud: ^3.4.7
  path: ^1.9.0
  provider: ^6.1.2
  macos_secure_bookmarks: ^0.2.1
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.17
  external_path: ^2.2.0
  on_audio_query: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mockito: ^5.6.1
  build_runner: ^2.10.4
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Press Start 2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
